import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Html } from "next/document";
import Navbar from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });
import AuthProvider from "./AuthProvider";

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar/>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
